import { Metadata } from "next"

//normal string metadata
// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

//object title metadata
export const metadata: Metadata = {
  title: {
    default: "Next.js Tutorial - Fauji",
    template:"%s | Fauji"
  }
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor: "lightblue",
            padding: "1rem",
            textAlign: "center"
          }}
        >
          <h4>Header</h4>
        </header>
        {children}
        <footer
          style={{
            backgroundColor: "lightgreen",
            padding: "1rem",
            textAlign: "center"
          }}
        >
          <h4>footer</h4>
        </footer>
      </body>

    </html>
  )
}
